kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8deployer-binding
subjects:
  - kind: User
    name: k8sdeployer
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: deployer
  apiGroup: ""
