kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: devedit-binding
  namespace: dev
subjects:
  - kind: User
    name: devedit
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: ""
