kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: devadmin-binding
  namespace: dev
subjects:
  - kind: User
    name: devadmin
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: ""
