kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: devusr2-binding
  namespace: dev
subjects:
  - kind: User
    name: devusr2
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: developer
  apiGroup: ""
