---
- name: Creating a repository file for Kubernetes
  file:
    path: /etc/yum.repos.d/kubernetes.repo
    state: touch

- name: Adding repository details in Kubernetes repo file.
  blockinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Installing Docker dependencies
  shell: yum install -y {{ item }}
  with_items: "{{ centosDockerPkgs }}"

- name: Adding docker repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Installing Docker packages
  shell: yum install -y {{ item }}
  with_items: "{{ centosDockerInstall }}"

- name: Installing Kubernetes packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ centosKubePackages }}"

- name: Installing additional packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ instPkgs | default([]) }}"

- name: Starting and Enabling the required services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ centosServices }}"

- name: Starting and Enabling additional services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ enblSvcs | default([]) }}"

- name: Allow Network Ports in Firewalld
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ ports }}"

- name: Allow Additional Network Ports in Firewalld
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ openPorts | default([]) }}"

- name: Enabling Bridge Firewall Rule
  shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
