---

- name: Create a user for kubernetes
  include_tasks: user.yml

- name: Update swap options
  include_tasks: prerequisites.yml

- name: Install Kubernetes dependencies 
  include_tasks: kubedependencies.yml
