---
- name: Check if file exists
  stat:
    path: "{{role_path}}/volcreation.yml"
  register: fileCheck

- name: Delete the file
  file:
    path: "{{role_path}}/volcreation.yml"
    state: absent
  when: fileCheck.stat.exists == True

- name: Copy yaml file
  template:
    src: volcreation.j2
    dest: "{{role_path}}/volcreation.yml"

- name: Create persistent volume
  shell: kubectl apply -f {{role_path}}/volcreation.yml
