---
- name: Creating a user for kubernetes, here a new user is created
  user: name="{{ kubeUser }}" append=yes state=present createhome=yes shell=/bin/bash

- name: allow new user to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: "{{ kubeUser }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: set up authorized keys for the new user
  authorized_key: user="{{ kubeUser }}" key="{{item}}"
  with_file:
    - ~/.ssh/id_rsa.pub

- name: set new user as the main username
  set_fact:
    user: "{{ kubeUser }}"
